json.id duel_monster.id
json.name duel_monster.name
json.level duel_monster.level
json.trait duel_monster.trait
json.kind duel_monster.kind
json.monster_catagory duel_monster.monster_catagory
json.attack duel_monster.attack
json.defense duel_monster.defense
json.card_artwork duel_monster.card_artwork
json.created_at duel_monster.created_at
json.updated_at duel_monster.updated_at
